# Generated by Django 3.2.7 on 2025-02-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('calm', models.CharField(max_length=150)),
                ('stress', models.CharField(max_length=150)),
                ('response_score', models.CharField(max_length=150)),
                ('confidence_score', models.CharField(max_length=150)),
                ('excitement', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='regtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('resume', models.CharField(max_length=150)),
            ],
        ),
    ]
