# Generated by Django 3.2.7 on 2025-02-06 17:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanalysis',
            name='resume_analysis',
            field=models.CharField(default=datetime.datetime(2025, 2, 6, 17, 27, 28, 549854, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
