# Generated by Django 3.2.7 on 2025-03-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interviewanalysis_resume_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='malpratice_detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=150)),
                ('malpractice', models.CharField(max_length=150)),
                ('proof', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='InterviewAnalysis',
        ),
    ]
