# Generated by Django 3.2.7 on 2025-03-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250311_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpratice_detection',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='malpratice_detection',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
