# Generated by Django 3.2.7 on 2025-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250325_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalpraticeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('malpractice', models.CharField(max_length=150)),
                ('proof', models.CharField(max_length=150)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='malpratice_detection',
        ),
    ]
