# Generated by Django 3.2.7 on 2025-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250325_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malpraticedetection',
            old_name='approved',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='malpraticedetection',
            name='is_malpractice',
            field=models.BooleanField(null=True),
        ),
    ]
