# Generated by Django 3.2.7 on 2025-03-27 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20250325_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='malpraticedetection',
            name='lecture_hall',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LectureHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('MAIN', 'Main Building'), ('KE', 'KE Block')], max_length=50)),
                ('hall_name', models.CharField(max_length=50)),
                ('assigned_teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='lecture_halls',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='app.LectureHall'),
        ),
    ]
