# Generated by Django 3.2.7 on 2025-03-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20250327_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='lecture_halls',
        ),
    ]
