# Generated by Django 3.2.7 on 2025-03-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_teacherprofile_lecture_halls'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='lecture_hall',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lecturehall'),
        ),
    ]
