# Generated by Django 3.2.7 on 2025-03-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_lecture_hall_teacherprofile_lecture_halls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='lecture_halls',
            new_name='lecture_hall',
        ),
    ]
