# Generated by Django 3.2.7 on 2025-03-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_lecture_halls_teacherprofile_lecture_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malpraticedetection',
            name='lecture_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lecturehall'),
        ),
    ]
