# Generated by Django 3.2.7 on 2025-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_malpraticedetection_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malpraticedetection',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
